// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Cron is the golang structure of table cron for DAO operations like Where/Data.
type Cron struct {
	g.Meta    `orm:"table:cron, do:true"`
	Id        interface{} // 主键
	Name      interface{} // 任务名称
	Params    interface{} // 函数参数
	Pattern   interface{} // 定时表达式
	Policy    interface{} // 策略
	Count     interface{} // 执行次数
	Sort      interface{} // 排序
	Remark    interface{} // 备注
	Status    interface{} // 状态
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
