// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// KnowledgeBase is the golang structure of table knowledge_base for DAO operations like Where/Data.
type KnowledgeBase struct {
	g.Meta            `orm:"table:knowledge_base, do:true"`
	Code              interface{} //
	FunctionPath      interface{} //
	ModuleName        interface{} //
	DescoveryVersion  interface{} //
	Summary           interface{} //
	ProblemDesc       interface{} //
	SuggestedSolution interface{} //
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
}
