// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Ticket is the golang structure of table ticket for DAO operations like Where/Data.
type Ticket struct {
	g.Meta      `orm:"table:ticket, do:true"`
	Id          interface{} //
	Code        interface{} // 工单号
	Title       interface{} // 工单标题
	Description interface{} // 问题描述
	CreatUserId interface{} // 创建人id
	Type        interface{} // 工单类型，0 问题工单，1 需求工单
	CreatedAt   *gtime.Time // 工单创建时间
	HandlerId   interface{} // 处理人id
	ReasonId    interface{} // 问题原因id
	DealReason  interface{} // 解决办法
	UpdatedAt   *gtime.Time // 更新时间
	Status      interface{} // 工单状态
}
