// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CronDao is the data access object for table cron.
type CronDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns CronColumns // columns contains all the column names of Table for convenient usage.
}

// CronColumns defines and stores column names for table cron.
type CronColumns struct {
	Id        string // 主键
	Name      string // 任务名称(唯一)
	Func      string // 调用的函数名称
	Params    string // 函数参数
	Pattern   string // 定时表达式
	Policy    string // 策略
	Count     string // 执行次数
	Sort      string // 排序
	Remark    string // 备注
	CreatedAt string // 创建时间
	UpdatedAt string // 更新时间
	Status    string // 状态
}

//  cronColumns holds the columns for table cron.
var cronColumns = CronColumns{
	Id:        "id",
	Name:      "name",
	Func:      "func",
	Params:    "params",
	Pattern:   "pattern",
	Policy:    "policy",
	Count:     "count",
	Sort:      "sort",
	Remark:    "remark",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Status:    "status",
}

// NewCronDao creates and returns a new DAO object for table data access.
func NewCronDao() *CronDao {
	return &CronDao{
		group:   "default",
		table:   "cron",
		columns: cronColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CronDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CronDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CronDao) Columns() CronColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CronDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CronDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CronDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
