// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_ticket/internal/model"
)

type ICron interface {
	StartCron(ctx context.Context)
	AddCronTask(ctx context.Context, in model.AddCronTaskInput) (err error)
}

var localCron ICron

func Cron() ICron {
	if localCron == nil {
		panic("implement not found for interface ICron, forgot register?")
	}
	return localCron
}

func RegisterCron(i ICron) {
	localCron = i
}
