// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_ticket/internal/model"
)

type IKnowledge interface {
	GetKnowledgeData(ctx context.Context, in model.KnowledgeListInput) (out *model.KnowledgeListOutput, err error)
}

var localKnowledge IKnowledge

func Knowledge() IKnowledge {
	if localKnowledge == nil {
		panic("implement not found for interface IKnowledge, forgot register?")
	}
	return localKnowledge
}

func RegisterKnowledge(i IKnowledge) {
	localKnowledge = i
}
