// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"github.com/gogf/gf/v2/net/ghttp"
)

type IMiddleware interface {
	I18NMiddleware(r *ghttp.Request)
	ResponseHandler(r *ghttp.Request)
	MiddlewareCORS(r *ghttp.Request)
	Ctx(r *ghttp.Request)
	TokenAuth(r *ghttp.Request)
}

var localMiddleware IMiddleware

func Middleware() IMiddleware {
	if localMiddleware == nil {
		panic("implement not found for interface IMiddleware, forgot register?")
	}
	return localMiddleware
}

func RegisterMiddleware(i IMiddleware) {
	localMiddleware = i
}
