// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IScheduled interface {
	GenerateKnowledgeJsonFile(ctx context.Context)
}

var localScheduled IScheduled

func Scheduled() IScheduled {
	if localScheduled == nil {
		panic("implement not found for interface IScheduled, forgot register?")
	}
	return localScheduled
}

func RegisterScheduled(i IScheduled) {
	localScheduled = i
}
