// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"go_ticket/internal/model"
)

type ITicket interface {
	CreateTicket(ctx context.Context, in model.CreateTicketInput) (err error)
}

var localTicket ITicket

func Ticket() ITicket {
	if localTicket == nil {
		panic("implement not found for interface ITicket, forgot register?")
	}
	return localTicket
}

func RegisterTicket(i ITicket) {
	localTicket = i
}
