// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go_ticket/internal/dao/internal"
)

// internalCronDao is internal type for wrapping internal DAO implements.
type internalCronDao = *internal.CronDao

// cronDao is the data access object for table cron.
// You can define custom methods on it to extend its functionality as you wish.
type cronDao struct {
	internalCronDao
}

var (
	// Cron is globally public accessible object for table cron operations.
	Cron = cronDao{
		internal.NewCronDao(),
	}
)

// Fill with you ideas below.
