// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go_ticket/internal/dao/internal"
)

// internalTicketDao is internal type for wrapping internal DAO implements.
type internalTicketDao = *internal.TicketDao

// ticketDao is the data access object for table ticket.
// You can define custom methods on it to extend its functionality as you wish.
type ticketDao struct {
	internalTicketDao
}

var (
	// Ticket is globally public accessible object for table ticket operations.
	Ticket = ticketDao{
		internal.NewTicketDao(),
	}
)

// Fill with you ideas below.
