// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// KnowledgeBase is the golang structure for table knowledge_base.
type KnowledgeBase struct {
	Code              string      `json:"code"              description:""`
	FunctionPath      string      `json:"functionPath"      description:""`
	ModuleName        string      `json:"moduleName"        description:""`
	DescoveryVersion  string      `json:"descoveryVersion"  description:""`
	Summary           string      `json:"summary"           description:""`
	ProblemDesc       string      `json:"problemDesc"       description:""`
	SuggestedSolution string      `json:"suggestedSolution" description:""`
	CreatedAt         *gtime.Time `json:"createdAt"         description:""`
	UpdatedAt         *gtime.Time `json:"updatedAt"         description:""`
}
