// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        int         `json:"id"        description:""`
	Name      string      `json:"name"      description:""`
	Password  string      `json:"password"  description:""`
	IsDelete  int         `json:"isDelete"  description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	IsAdmin   int         `json:"isAdmin"   description:""`
	RoleId    int         `json:"roleId"    description:""`
}
