// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserRole is the golang structure for table user_role.
type UserRole struct {
	Id          int64       `json:"id"          description:""`
	UserId      int64       `json:"userId"      description:"用户id"`
	RoleId      int64       `json:"roleId"      description:"角色id"`
	IsDelete    int         `json:"isDelete"    description:"是否删除"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:"创建时间"`
	UpdatatedAt *gtime.Time `json:"updatatedAt" description:"更新时间"`
}
